### ISSUE TITLE
prompt = 'Once upon a time' ERROR: 

### ISSUE THREAD

**Issue by pvsundar** [samterfa/openai#2]
Error in `map_chr()`:
ℹ In index: 1.
ℹ With name: text.
Caused by error in `.x$text`:
! $ operator is invalid for atomic vectors
Run `rlang::last_trace()` to see where the error occurred.

create_completion(
     model = 'davinci', 
     max_tokens = 30,
     temperature = .5,
     top_p = 1,
     n = 1,
     stream = F, 
     prompt = 'Once upon a time') %>% 
     pluck('choices') %>% 
     map_chr(~ .x$text)

I have NO idea how to fix this.

**Comment by samterfa** [comment]
Can you run just this part and let me know what it returns?
```
create_completion(
model = 'davinci',
max_tokens = 30,
temperature = .5,
top_p = 1,
n = 1,
stream = F,
prompt = 'Once upon a time')
```

**Comment by pvsundar** [comment]
this works now. Ammended:
create_completion(
     model = 'davinci',
     max_tokens = 30,
     temperature = .5,
     top_p = 1,
     n = 1,
     stream = F,
     prompt = 'Once there was a pink giant who loved ice-cream') %>%
     pluck('choices') %>%
     map_chr(~ .x$text)
[1] ", but he was a bit of a klutz, and he always managed to drop the cone before he could get it to his mouth. One"
