### ISSUE TITLE
I got error when I tried to apply the code after I set up the user ID and key

### ISSUE THREAD

**Issue by czqiu** [samterfa/openai#3]
library(openai)
library(purrr)
library(magrittr)
library(dplyr)

list_models() %>% pluck('data') %>% map_dfr(compact)

Show in New Window
 Error in namespaceExport(ns, exports) : 
undefined exports: %has_args%, %has_attr%, %has_name%, on_failure<-, are_equal, assert_that, has_args, has_attr, has_extension, has_name, is.count, is.date, is.dir, is.error, is.flag, is.number, is.readable, is.scalar, is.string, is.time, is.writeable, noNA, not_empty, on_failure, see_if, validate_that

**Comment by samterfa** [comment]
Hi, can you restart your R session, and then try just the code below and let me know what happens?

```
library(openai)
library(purrr)
library(magrittr)
library(dplyr)

list_models()
```

**Comment by czqiu** [comment]
Hi Sameterfa,

I still got the same error:

[cid:502efb3b-e7ce-4933-8b17-438320420908]

Thanks
Eric
________________________________

**Comment by samterfa** [comment]
This error appears different than the last one. Can you please install the [reprex package](https://reprex.tidyverse.org/) and run the following. It will put the results of running the code on your computer's clipboard. Please paste the results in your next submission. Thanks!

```
reprex::reprex({
library(openai)
library(purrr)
library(magrittr)
library(dplyr)

list_models()
})
```

**Comment by samterfa** [comment]
Any luck creating a [reprex](https://reprex.tidyverse.org/)?
