### ISSUE TITLE
Autocomplete R code addin

### ISSUE THREAD

**Issue by mayrfb** [samterfa/openai#4]
When typing the prompt "Load mtcars data and create boxplot" in the console, I receive the following return:
Here's how to load the `mtcars` data and create a basic boxplot of the `mpg` variable using R:
Error: unexpected symbol in "load mtcars"

I am using R 4.2.3 with most recent version of R studio and Windows 11

**Comment by samterfa** [comment]
Hi, when you run the addin, the model may return code that doesn't work properly. It's hit and miss with the model; I will likely change it to not automatically execute to not confuse users. You can press the up key in RStudio to inspect the code and find the error if that happens. Let me know if that doesn't make sense.
