### ISSUE TITLE
how to make addin work after type # write some R code ...

### ISSUE THREAD

**Issue by whiteorchid** [samterfa/openai#5]
Dear author,

Thanks a lot for your great tool!

May I have your guidance that how to make the add-in work? After library(openai), and then type # write some R code ..., no code is generated automatically, is it due to the addin content interactive: False? 

Many thanks!

**Comment by whiteorchid** [comment]
```
Error in (function (prompt = rstudioapi::getConsoleEditorContext()$contents,  : 
list(message = "This model's maximum context length is 4097 tokens. However, you requested 4105 tokens (70 in the messages, 4035 in the completion). Please reduce the length of the messages or completion.", type = "invalid_request_error", param = "messages", code = "context_length_exceeded")
```

Thanks a lot! It seems when I click the autocomplete in the addin, it automatically read all the scripts, not the row I chose, when type the # write some R code in the console, it do not generate the new scripts. 

Then I first run rm(list = ls()), to clean all other elements, library(openai), and # write some R codes to get overlap of several list, shows the same error...

Is it possible that the autocomplete can run in the middle of the scripts based on the context, say # write some R code for get the overlap of list1, list2, list3, list4, which was generated by the first part of R scripts. 

Thank you very much for your guidance!

**Comment by kaanokay** [comment]
Hi @samterfa,

I have the same issue. I wonder whether its possible to add more detailed tutorial of how addin works when writing some in text as comment to generate codes automatically.

Thank you!

**Comment by samterfa** [comment]
As of now, the addin only works in the console interactively as demonstrated in the gif of the README. It can easily be updated to use code from a .R file but that's not how it works currently. 

Also, the model can only be fed a certain amount of text (4096 tokens). This is a limitation of the OpenAI model itself. If you feed it more than that you will see the above error. This includes past requests you've made of the model. You will need to remove the openai_completions and openai_completions_usage variables in the global environment to reset the conversation. I'll be changing that soon.

**Comment by whiteorchid** [comment]
Thanks a lot! Thank you for your guidance and the amazing tool!
