### ISSUE TITLE
error when clicking on addin

### ISSUE THREAD

**Issue by arcj-hub** [samterfa/openai#7]
HI!

I am trying to use this very cool tool but get the following error when I try to add the addin.

Error in (function (prompt = rstudioapi::getConsoleEditorContext()$contents,  : 
  list(message = "You exceeded your current quota, please check your plan and billing details.", type = "insufficient_quota", param = NULL, code = NULL)

<img width="728" alt="Screen Shot 2023-04-12 at 4 08 19 PM" src="https://user-images.githubusercontent.com/82059281/231605357-fdce183f-0ac5-4a43-b151-f91b24d4bd3f.png">

**Comment by samterfa** [comment]
That's a bummer. That error is actually returned by OpenAI. Have you ever used the addin or OpenAI API successfully before? One Google search result mentioned that people sometimes get this error if they haven't [set up a payment plan](https://platform.openai.com/account/billing/overview) for their API usage. Does that apply to you?

**Comment by samterfa** [comment]
No problem. It is very inexpensive and completely worth it in my opinion. You might spend a couple bucks in a month.
